tap "dracula/install"
tap "homebrew/bundle"
tap "homebrew/services"
brew "arp-scan"
brew "bash-completion"
brew "bat"
brew "coreutils"
brew "dua-cli"
brew "eza"
brew "fzf"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "go"
brew "goto"
brew "grep"
brew "htop"
brew "hugo"
brew "imagemagick"
brew "ipcalc"
brew "lsd"
brew "mas"
brew "nmap"
brew "pinentry-mac"
brew "pyenv"
brew "starship"
brew "telnet"
brew "tidy-viewer"
brew "tree"
brew "wget"
brew "xxh"
brew "yadm"
brew "zsh"
brew "zsh-completions"
cask "appcleaner"
cask "asana"
cask "battery"
cask "blockblock"
cask "brave-browser"
cask "canva"
cask "cloudflare-warp"
cask "codeedit"
cask "copilot"
cask "coteditor"
cask "discord"
cask "dracula-terminal"
cask "equinox"
cask "exifcleaner"
cask "fantastical"
cask "firefox"
cask "font-caskaydia-mono-nerd-font"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "font-roboto-mono-nerd-font"
cask "fork"
cask "gpg-suite-no-mail"
cask "hiddenbar"
cask "iina"
cask "iterm2"
cask "itsycal"
cask "keka"
cask "keyclu"
cask "latest"
cask "logi-options+"
cask "lulu"
cask "microsoft-edge"
cask "mist"
cask "monitorcontrol"
cask "mos"
cask "notion"
cask "onyx"
cask "ransomwhere"
cask "rectangle"
cask "shottr"
cask "silentknight"
cask "utm"
cask "visual-studio-code"
cask "zoom"
mas "Adblock Plus", id: 1432731683
mas "Amphetamine", id: 937984704
mas "Bear", id: 1091189122
mas "Bitwarden", id: 1352778147
mas "Ghostery Privacy Ad Blocker", id: 6504861501
mas "Pixelmator Pro", id: 1289583905
mas "Prime Video", id: 545519333
mas "Pure Paste", id: 1611378436
mas "Slack", id: 803453959
mas "Todoist", id: 585829637
vscode "dracula-theme.theme-dracula"
